// Code generated by goctl. DO NOT EDIT.
package types

type FileUploadReq struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size int64  `json:"size,optional"`
	Path string `json:"path,optional"`
}

type FileUploadResp struct {
	Identity string `json:"identity"`
	Ext      string `json:"ext"`
	Name     string `json:"name"`
}

type InfoRequest struct {
	Identity string `json:"identity"`
}

type InfoResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type McsRequest struct {
	Email string `json:"email"`
}

type McsResponse struct {
	Code string `json:"code"`
}

type UflReq struct {
	Id   int64 `json:"id,optional"`
	Page int   `json:"page,optional"`
	Size int   `json:"size,optional"`
}

type UflResp struct {
	List  []*UserFiles `json:"list"`
	Count int64        `json:"count"`
}

type UrsReq struct {
	ParentId           int64  `json:"parentId"`
	RepositoryIdentity string `json:"repositoryIdentity"`
	Ext                string `json:"ext"`
	Name               string `json:"name"`
}

type UrsResp struct {
}

type UserFiles struct {
	Id                 int64  `json:"id"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Path               string `json:"path"`
	Size               int64  `json:"size"`
	Identity           string `json:"identity"`
	RepositoryIdentity string `json:"repositoryIdentity"`
}

type UserRegisterRequest struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	Email      string `json:"email"`
	VerifyCode string `json:"verifycode"`
}

type UserRegisterResponse struct {
}
